### ISSUE TITLE
Http 400 on Issue Asset transaction on TestNet

### ISSUE THREAD

**Issue by layinka** [wavesplatform/WavesCS#17]
Hi,
I am trying to issue a custom asset on the testnet using the issue transaction, but i keep getting an Http 400 error.

Any solution?

**Comment by d-kiselev** [comment]
Hi @layinka,
You might try to create a new account:
   ```C#
Node node = new Node(Node.TestNetHost);
   var account = PrivateKeyAccount.CreateFromSeed(PrivateKeyAccount.GenerateSeed(), AddressEncoding.TestNet);
   var address = account.Address;
   var privateKey = account.PrivateKey.ToBase58();

   Console.WriteLine($“Address: { address}“);
   Console.WriteLine($“Private key: { privateKey}“);

```
The output has to be something like this:

>        Address: 3N29CedUAxVxybCMWsDCMwUe2Ky2AL3mMeE
>        Private key: 8ZZciAp6MhritHR3h5RSJB3P3aXKT6VJtSRKX1Yrd8ib

Make sure your balance is enough to issue a new asset. You can use [Faucet](https://testnet.wavesexplorer.com/faucet) to get coins.

To issue a new asset do the following (use previously created account):
   ```C#
Node node = new Node(Node.TestNetHost);
   var account = PrivateKeyAccount.CreateFromPrivateKey(“8ZZciAp6MhritHR3h5RSJB3P3aXKT6VJtSRKX1Yrd8ib”, AddressEncoding.TestNet);

   Asset asset = node.IssueAsset(account, “testAsset”, “asset for c# issue testing”, 2, 6, true);
   Assert.IsNotNull(asset);
```
