### ISSUE TITLE
Currency pair must be mirrored

### ISSUE THREAD

**Issue by GillesChamp** [wavesplatform/WavesCS#3]
Hi, thanks for great job. 
With little modification I was able to put an order, on my node, however to avoid returned error **" Invalid AssetPair ordering, should be reversed"** the currency pair must be submitted mirrored respect the pair normally processed using the wallet. In order to fill the order  I used a local Gui  0.5.10a that also shows the  pair in the same manner, forcing an automatic reversing. 
**Could it be an issue related to the matcher configuration ?**

**Comment by d-kiselev** [comment]
Unfortunately, we are not able to support changing the order in the CS library. There is the different logic of verifying the asset pair ordering in TestNet and MainNet configuration files.

Thus, the only solution when getting this error is to simply change the ordering of assets.
