### ISSUE TITLE
Order Constructor Not Updated in Nuget?

### ISSUE THREAD

**Issue by sillyghost** [wavesplatform/WavesCS#32]
Heya , 
I installed the latest Nuget package and was trying to create order's but the order constructor is different from the one here , it has arguments like Id etc , was trying the exchange.cs example ! but the constructor arguments weren't matching up ! Btw Nice package its really helpful !

**Comment by CurufinweU** [comment]
Hi,

I can also confirm this issue:
It seems that updated nuget packages v. 1.1.0.4 and v. 1.1.0.5 contain updated source files but the binaries (WavesCS.dll) are old. For example if you try to use nuget v. 1.1.0.5 - there is still no method TransactionExtensons.GenerateId!

**Comment by sillyghost** [comment]
Ya after i wrote that found that many things were not updated , hopefully will be updated soon!

**Comment by d-kiselev** [comment]
The binaries were updated in version 1.1.0.6.
