### ISSUE TITLE
Getting 404 through Node.broadcast

### ISSUE THREAD

**Issue by sillyghost** [wavesplatform/WavesCS#35]
Using the latest version on nuget found that whenever i try to use the broadcast exchange transaction ,i am getting 404 not found error every time i try that ! Is this is a issue with the node or the Library?

**Comment by d-kiselev** [comment]
Hi,
Thanks for your report!
We've fixed some parsing bugs. Try to download the latest version from nuget (1.1.1.2). Does this solve the issue?

**Comment by sillyghost** [comment]
yes worked , closing issue :)
