### ISSUE TITLE
add pagination to node.GetTransactions

### ISSUE THREAD

**Issue by djpnewton** [wavesplatform/WavesCS#39]
There is an "after" (transaction id) parameter

**Comment by djpnewton** [comment]
Oh it looks like its broken, but will be fixed in a new release: https://github.com/wavesplatform/Waves/pull/1971

**Comment by d-kiselev** [comment]
There's a separate method for this: `Node.GetTransactionsByAddressAfterId(string address, string afterId, int limit = 100)`
