### ISSUE TITLE
proposal for changes to support .net core

### ISSUE THREAD

**Issue by nexon33** [wavesplatform/WavesCS#41]
please in Http.cs change

`
public static string GetJson(string url, NameValueCollection headers = null)
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
`
to

`public static string GetJson(string url, NameValueCollection headers = null)
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;`

since `SecurityProtocolType.Ssl3` Is not supported and is obsolete in .net core, if those changes are applied all of the functions I tested also work in .net core 2.2. Altrough some functionality might still be missing this would already fix a lot of api related stuff and make the library usable on .net core.

**Comment by djpnewton** [comment]
I have had to patch my local version like this, maybe it could be a conditional compile.. but its probably better to just remove it as SSL3 is not deemed secure any more

**Comment by d-kiselev** [comment]
Sorry for the long delay and thank you for your proposal, `SecurityProtocolType.Ssl3` has been removed.
