### ISSUE TITLE
Wrong fee for Smart Account causes run time error

### ISSUE THREAD

**Issue by blockxperts** [wavesplatform/WavesCS#43]
The Node.Transfer() method assumes only the transaction fee is fixed at 0.001 + 0.004 for smart assets. However you didn't consider smart accounts. This causes error when sending from address with embedded script. I came up with a new Node.CalculateFee that accurately adjusts the transaction fee even if Transfer() is called with null fee. This needs to be applied also for MassTransfer(). Also we still need to adjust the calculator to return Sponsored fee in the desired asset not just WAVES. For now it only assumes all fees are in WAVES asset.

```
        public decimal CalculateFee(TransferTransaction transaction, Asset asset, PrivateKeyAccount sender, Node node, decimal? fee = null)
        {
            decimal defaultFee = 0.001m;
            decimal baseFee = fee ?? defaultFee;
            decimal extraFee = asset.Script != null ? 0.004m : node.GetAddressExtraFee(sender.Address);
            decimal txnFee = Math.Max(asset.LongToAmount(node.CalculateFee(transaction)), defaultFee + extraFee);
            return Math.Max(txnFee, baseFee);
        }


        public string Transfer(PrivateKeyAccount sender, string recipient, Asset asset, decimal amount, string message = "")
        {
            var tx = new TransferTransaction(ChainId, sender.PublicKey, recipient, asset, amount, message);
            tx.Fee = CalculateFee(tx, asset, sender, this);
            tx.Sign(sender);
            return Broadcast(tx);
        }


        public string Transfer(PrivateKeyAccount sender, string recipient, Asset asset, decimal amount,
                               decimal fee, Asset feeAsset = null, byte[] message = null)
        {
            var tx = new TransferTransaction(ChainId, sender.PublicKey, recipient, asset, amount, fee, feeAsset, message);
            tx.Fee = CalculateFee(tx, feeAsset ?? asset, sender, this, fee);
            tx.Sign(sender);
            return Broadcast(tx);
        }


        public decimal GetAddressExtraFee(string address)
        {
            return GetObject($"addresses/scriptInfo/{address}").GetDecimal("extraFee", Assets.WAVES);
        }
```

**Comment by d-kiselev** [comment]
Hi,
Thanks for your contribution! Node already has API method that calculates fee, so we've fixed the calculation via using that method: https://github.com/wavesplatform/WavesCS/commit/28e793f8d3d4033a2cba296815b505bde6f31ec4
The second method `Transfer(PrivateKeyAccount sender, string recipient, Asset asset, decimal amount, decimal fee, Asset feeAsset = null, byte[] message = null)` has customisable fee and is intended for use with custom fee.
