### ISSUE TITLE
Error message not returned

### ISSUE THREAD

**Issue by njale** [wavesplatform/WavesCS#46]
If doing a transaction on a blocked account in JavaScript the returned error is "Transaction is not allowed by account-script.". If doing the exact same transaction through your C# library, it returns "The remote server returned an error: (400) Bad Request". This is not very helpful and to me it looks like this message is returned for any error. 

Example:
string result = node.Transfer(account, recipientAddress, Assets.WAVES, 1);

Ride Account-script:

@Verifier(tx)
func verify() = {
    match tx {
        case d: SetScriptTransaction => true
        case d: DataTransaction => true
        case _ => false
    }
}

**Comment by d-kiselev** [comment]
Hi,
now **Http.Post** method throws an exception with a specific error message that can be caught later. There's an example in **WavesCSTests.SetScriptTest.TestErrorMessage**.
