### ISSUE TITLE
Support at least .NET 4.0

### ISSUE THREAD

**Issue by Tolsi** [wavesplatform/WavesCS#9]

**Comment by d-kiselev** [comment]
Currently, we support .NET 4.5.1.

**Comment by username1565** [comment]
Maybe just need to add some functions or class inside CS-files, to support .NET Framework 4.0

**Comment by d-kiselev** [comment]
We use PCLCrypto 2.0.147 as a dependency, which is not compatible with .NET 4.0 (requires .NET 4.5).
